config/routes.rb
#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
  end


  
  resources :projects do 
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do 
        get :contacts_notes
      end
    end
    resources :contact_imports, :only => [:new, :create]
    resources :deal_imports, :only => [:new, :create]

  end
  
  resources :deals do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email
      post :bulk_edit, :bulk_update, :send_mails
      delete :bulk_destroy
    end
  end

  resources :projects do 
    resources :deals, :only => [:new, :create, :index]
  end

  resources :projects do 
    resources :contacts_queries, :only => [:new, :create]
  end  

  resources :contacts_queries, :except => [:show]

  resources :deal_statuses, :except => :show do
    collection do
      put :assing_to_project
    end
  end

  match 'projects/:project_id/contacts/:contact_id/new_task' => 'contacts_tasks#new', :via => :post

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index'

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new'
 
  match 'projects/:project_id/sales_funnel'  => 'sales_funnel#index'
  match 'sales_funnel/:action' => 'sales_funnel#index'

  match 'notes/:note_id' => 'notes#show', :via => :get
  match 'notes/show/:note_id' => 'notes#show', :via => :get
  match 'notes/:note_id/edit' => 'notes#edit', :via => :get
  match 'notes/:note_id/update' => 'notes#update', :via => :put
  match 'notes/:note_id/destroy_note' => 'notes#destroy_note'
  match 'notes/add_note' => 'notes#add_note'
  match 'notes/destroy' => 'notes#destroy'
  
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'
  
  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates'
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_projects/:action' => 'contacts_projects'
  match 'contacts_tags/:action' => 'contacts_tags'
  match 'contacts_tasks/:action' => 'contacts_tasks'
  match 'contacts_vcf/:action' => 'contacts_vcf'
  match 'deal_categories/:action' => 'deal_categories'
  match 'deal_contacts/:action' => 'deal_contacts'
  match 'deals_tasks/:action' => 'deals_tasks'
  match 'contacts_settings/:action' => 'contacts_settings'
  match 'contacts_mailer/:action' => 'contacts_mailer'
  match 'deals_tasks/:action' => 'deals_tasks'
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

    

app/models/deal.rb
class Deal < ActiveRecord::Base  
  unloadable       
    
  belongs_to :project   
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
  belongs_to :assigned_to, :class_name => 'User', :foreign_key => 'assigned_to_id'    
  belongs_to :category, :class_name => 'DealCategory', :foreign_key => 'category_id'
  belongs_to :contact  
  belongs_to :status, :class_name => "DealStatus", :foreign_key => "status_id"  
  has_many :deals, :class_name => "deal", :foreign_key => "reference_id"
  has_many :notes, :as => :source, :class_name => 'DealNote', :dependent => :delete_all, :order => "created_on DESC"
  has_many :deal_processes, :dependent => :delete_all
  has_and_belongs_to_many :related_contacts, :class_name => 'Contact', :order => "#{Contact.table_name}.last_name, #{Contact.table_name}.first_name", :uniq => true
  scope :visible, lambda {|*args| { :include => :project,
                                          :conditions => Project.allowed_to_condition(args.first || User.current, :view_deals)} }                
  
  scope :deletable, lambda {|*args| { :include => :project, 
                                            :conditions => Project.allowed_to_condition(args.first || User.current, :delete_deals) }}

  scope :live_search, lambda {|search| {:conditions =>   ["(#{Deal.table_name}.name LIKE ?)", "%#{search}%"] }}
  
  scope :open, :include => :status, :conditions => ["(#{DealStatus.table_name}.status_type = ? OR #{DealStatus.table_name}.status_type IS NULL)", DealStatus::OPEN_STATUS]
  scope :closed, joins(:status).where("#{DealStatus.table_name}.status_type <> #{DealStatus::OPEN_STATUS}")
  scope :won, :include => :status, :conditions => ["#{DealStatus.table_name}.status_type = ?", DealStatus::WON_STATUS]
  scope :lost, :include => :status, :conditions => ["#{DealStatus.table_name}.status_type = ?", DealStatus::LOST_STATUS]
  scope :was_in_status, lambda{|status_id| joins(:deal_processes).where(["#{DealProcess.table_name}.old_value = ? OR #{DealProcess.table_name}.value = ?", status_id, status_id]).uniq}
  
  acts_as_customizable
  acts_as_viewable
  acts_as_watchable
  acts_as_attachable :view_permission => :view_deals,
                     :delete_permission => :edit_deals   
                     
  acts_as_event :datetime => :created_on,
               :url => Proc.new {|o| {:controller => 'deals', :action => 'show', :id => o}}, 	
               :type => 'icon-add-deal',  
               :title => Proc.new {|o| o.name },
               :description => Proc.new {|o| [o.price_to_s, o.contact ? o.contact.name : nil, o.background].join(' ').strip } 

  acts_as_activity_provider :type => 'deals',               
                            :permission => :view_deals,  
                            :author_key => :author_id,
                            :find_options => {:include => :project}                     

  acts_as_searchable :columns => ["#{table_name}.name",  
                                  "#{table_name}.background"], 
                      :include => [:project],
                      # sort by id so that limited eager loading doesn't break with postgresql
                      :order_column => "#{table_name}.id"
  
                     

  validates_presence_of :name   
  validates_numericality_of :price, :allow_nil => true 
  
  after_update :create_deal_process
  after_update :send_notify_update
  after_create :send_notify_create


     
  
  include ActionView::Helpers::NumberHelper
  include ::DealsHelper

  def send_notify_update
    Mailer.crm_deal_updated(self).deliver if self.status_id_changed? && Setting.notified_events.include?('crm_deal_updated')
  end

  def send_notify_create
    Mailer.crm_deal_add(self).deliver if Setting.notified_events.include?('crm_deal_added')
  end
  
  def after_initialize
    if new_record?
      # set default values for new records only
      self.status ||= DealStatus.default
    end
  end
  
  def avatar
    
  end
   
  def expected_revenue
    self.probability ? (self.probability.to_f / 100) * self.price : self.price
  end

  def full_name
    result = ''
    result << self.contact.name + ": " unless self.contact.blank?
    result << self.name
  end
  
  def all_contacts
    @all_contacts ||= ([self.contact] + self.related_contacts ).uniq
  end
      
  def self.available_users(prj=nil)  
    cond = "(1=1)"  
    cond << " AND #{Deal.table_name}.project_id = #{prj.id}" if prj
    User.active.find(:all, :select => "DISTINCT #{User.table_name}.*", :joins => "JOIN #{Deal.table_name} ON #{Deal.table_name}.assigned_to_id = #{User.table_name}.id", :conditions => cond, :order => "#{User.table_name}.lastname, #{User.table_name}.firstname")
  end 
  
  def open?
    self.status.blank? || self.status.is_open?
  end
  
  def init_deal_process(author)
    @current_deal_process ||= DealProcess.new(:deal => self, :author => (author || User.current))
    @deal_status_before_change = self.new_record? ? nil : self.status_id
    updated_on_will_change!  
    @current_deal_process
  end
  
  def create_deal_process
    if @current_deal_process && @deal_status_before_change && !(@deal_status_before_change == self.status_id)
      @current_deal_process.old_value = @deal_status_before_change
      @current_deal_process.value = self.status_id 
      @current_deal_process.save
      # reset current journal
      init_deal_process @current_deal_process.author
    end
  end   
  
  def visible?(usr=nil)
    (usr || User.current).allowed_to?(:view_deals, self.project)
  end    
  
  def editable?(usr=nil)
    (usr || User.current).allowed_to?(:edit_deals, self.project)
  end

  def destroyable?(usr=nil)
    (usr || User.current).allowed_to?(:delete_deals, self.project)
  end

  # Returns an array of projects that user can move deal to
  def self.allowed_target_projects(user=User.current)
    Project.all(:conditions => Project.allowed_to_condition(user, :add_deals))
  end
    

  # Returns the mail adresses of users that should be notified
  def recipients
    notified = []
    # Author and assignee are always notified unless they have been
    # locked or don't want to be notified
    notified << author if author
    if assigned_to
      notified += (assigned_to.is_a?(Group) ? assigned_to.users : [assigned_to])
    end
    notified = notified.select {|u| u.active? && u.notify_about?(self)}

    notified += project.notified_users
    notified.uniq!
    # Remove users that can not view the contact
    notified.reject! {|user| !visible?(user)}
    notified.collect(&:mail)
  end

  def status_was
    if status_id_changed? && status_id_was.present?
      @status_was ||= DealStatus.find_by_id(status_id_was)
    end
  end

  def price_to_s
    return '' if self.price.blank?
    Money.from_float(self.price, self.currency).format rescue helpers.number_with_delimiter(price, :delimiter => ' ', :precision => 2)    
  end

  def info  
   result = ""
   result = self.status.name if self.status
   result = result + " - " + self.price_to_s unless self.price.blank?    
   result
  end

  private

  def helpers
    ActionController::Base.helpers
  end  
end

app/helpers/deals_helper.rb
# encoding: utf-8
module DealsHelper
  def collection_for_status_select
    deal_statuses.collect{|s| [s.name, s.id.to_s]}
  end 
  
  def deal_status_options_for_select(select="")    
     options_for_select(collection_for_status_select, select)
  end  
  
  def deals_sum_to_currency(deals_sum)
    deals_sum.collect{|c| content_tag(:span, price_to_currency(c[1], c[0], :symbol => true), :style => "white-space: nowrap;")}.join(' / ').html_safe 
  end
  
  def deal_currency_icon(deal)
    case deal.currency.to_s.upcase
    when 'USD' 
      "icon-money-dollar"
    when 'EUR' 
      "icon-money-euro"
    when 'GBP' 
      "icon-money-pound"
    when 'RUB' 
      "icon-money"
    when 'JPY'
      "icon-money-yen"
    else
      "icon-money"
    end
  end

  def collection_for_currencies_select(default_currency = :usd)
    major_currencies(default_currency)
  end

  def major_currencies(default_currency)
    arr = []
    [default_currency.blank? ? nil : default_currency.to_s, :usd, :eur, :gbp, :rub, :jpy, :chf, :sgd].compact.each do |currency_code|
      currency = Money::Currency.find(currency_code)
      arr << ["#{currency.name} (#{currency.symbol})", currency.iso_code] if currency
    end
    arr.uniq
  end  

  def all_currencies
    Money::Currency.table.inject([]) do |array, (id, attributes)|
      array ||= []
      array << ["#{attributes[:name]}" + (attributes[:symbol].blank? ? "" : " (#{attributes[:symbol]})"), attributes[:iso_code]]
      array
    end.sort{|x, y| x[0] <=> y[0]}
  end  
  
  def price_to_currency(price, currency, options={})
    return '' if price.blank?

    Money.from_float(price, currency).format(options) rescue number_with_delimiter(price, :delimiter => ' ', :precision => 2)
  end
  
  def deal_price(deal)
    price_to_currency(deal.price, deal.currency, :symbol => true).to_s
  end
  
  def deal_statuses
    (!@project.blank? ? @project.deal_statuses : DealStatus.all(:order => "#{DealStatus.table_name}.status_type, #{DealStatus.table_name}.position")) || []
  end  
  
  def remove_contractor_link(contact) 
    link_to(image_tag('delete.png'), 
		  {:controller => "deal_contacts", :action => 'delete', :project_id => @project, :deal_id => @deal, :contact_id => contact}, 
			:remote => true,
      :method => :delete, 
			:confirm => l(:text_are_you_sure),	
			:class  => "delete", :title => l(:button_delete)) if  User.current.allowed_to?(:edit_deals, @project)
  end    
  
  def retrieve_date_range(period)   
    @from, @to = nil, nil
    case period 
    when 'today'
      @from = @to = Date.today
    when 'yesterday'
      @from = @to = Date.today - 1
    when 'current_week'
      @from = Date.today - (Date.today.cwday - 1)%7
      @to = @from + 6
    when 'last_week'
      @from = Date.today - 7 - (Date.today.cwday - 1)%7
      @to = @from + 6
    when '7_days'
      @from = Date.today - 7
      @to = Date.today
    when 'current_month'
      @from = Date.civil(Date.today.year, Date.today.month, 1)
      @to = (@from >> 1) - 1
    when 'last_month'
      @from = Date.civil(Date.today.year, Date.today.month, 1) << 1
      @to = (@from >> 1) - 1
    when '30_days'
      @from = Date.today - 30
      @to = Date.today
    when 'current_year'
      @from = Date.civil(Date.today.year, 1, 1)
      @to = Date.civil(Date.today.year, 12, 31)
    end    
    
    @from, @to = @from, @to + 1 if (@from && @to)
        
  end
  
  def deal_status_tag(deal_status)
    status_tag = content_tag(:span, deal_status.name) 
    content_tag(:span, status_tag, :class => "deal-status tags", :style => "background-color:#{deal_status.color_name};color:white;")
  end  
  
  
  def retrieve_deals_query
    # debugger
    # params.merge!(session[:deals_query])
    # session[:deals_query] = {:project_id => @project.id, :status_id => params[:status_id], :category_id => params[:category_id], :assigned_to_id => params[:assigned_to_id]}
    if params[:status_id] || !params[:period].blank? || !params[:category_id].blank? || !params[:assigned_to_id].blank? 
      session[:deals_query] = {:project_id => (@project ? @project.id : nil), 
                               :status_id => params[:status_id], 
                               :category_id => params[:category_id], 
                               :period => params[:period],
                               :assigned_to_id => params[:assigned_to_id]}
    else
      if api_request? || params[:set_filter] || session[:deals_query].nil? || session[:deals_query][:project_id] != (@project ? @project.id : nil)
        session[:deals_query] = {}
      else
        params.merge!(session[:deals_query])
      end
    end
  end

  def deals_to_csv(deals)
    decimal_separator = l(:general_csv_decimal_separator)
    encoding = 'utf-8'
    export = FCSV.generate(:col_sep => l(:general_csv_separator)) do |csv|
      # csv header fields
      headers = [ "#",
                  l(:field_name, :locale => :en),
                  l(:field_background, :locale => :en),
                  l(:field_currency, :locale => :en),
                  l(:field_price, :locale => :en), 
                  l(:label_crm_probability, :locale => :en), 
                  l(:label_crm_expected_revenue, :locale => :en), 
                  l(:field_due_date, :locale => :en), 
                  l(:field_author, :locale => :en),     
                  l(:field_assigned_to, :locale => :en),     
                  l(:field_status, :locale => :en),
                  l(:field_contact, :locale => :en),
                  l(:field_category, :locale => :en),   
                  l(:field_created_on, :locale => :en),
                  l(:field_updated_on, :locale => :en),
                  ]

      custom_fields = DealCustomField.all
      custom_fields.each {|f| headers << f.name}
      csv << headers.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      # csv lines
      deals.each do |deal|
        fields = [deal.id,
                  deal.name,
                  deal.background,
                  deal.currency,
                  deal.price,
                  deal.probability,
                  deal.expected_revenue,
                  format_date(deal.due_date),
                  deal.author,
                  deal.assigned_to,
                  deal.status,
                  deal.contact,
                  deal.category,
                  format_date(deal.created_on),
                  format_date(deal.updated_on)
                  ]
        custom_fields.each {|f| fields << show_value(deal.custom_value_for(f)) }
        csv << fields.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }                  
      end
    end
    export
  end

  
  
end

app/views/deals/_attributes.html.erb
<% if @deal.custom_values.any? %>
<div id="attributes">

	<h3><%= l(:label_deal) %></h3>  
	<table class="attributes">    
		<% @deal.custom_values.each do |custom_value| %>
			<% if !custom_value.value.blank? %>
			<tr> <th class = "custom_field"><%= custom_value.custom_field.name %>:</th><td> <%=h show_value(custom_value) %></td> </tr>
			<% end %>
		<% end %>
	</table>

</div>
<% end %>

app/views/deals/_custom_field_filter.html.erb
<span class="filter-condition">       
  available_custom_fields 
				<%= label_tag l(:label_assigned_to) + " "  %> 
				<%= select_tag :assigned_to_id, options_for_select(Deal.available_users(@project).collect{|u| [u.name, u.id.to_s]}.insert(0, [""]),  params[:assigned_to_id]) %>
</span>

app/views/deals/_custom_field_form.html.erb
<p><%= form.check_box :is_for_all %></p>
<p><%= form.check_box :is_filter %></p>
<p><%= form.check_box :visible, :label => l(:label_contacts_show_in_list) %></p>

app/views/deals/_deals_statistics.html.erb
<% if deal_statuses.any? %>      
	<div id="deals_statistics">  
		<% if !(@project && !authorize_for(:sales_funnel, :index)) %> 
			<div class="contextual">
				<%= link_to l(:label_sales_funnel), {:controller => 'sales_funnel', :action => 'index', :project_id => @project} %>
			</div>
		<% end %>
		<h3><%= l(:label_statistics) %></h3>
		<table class="deals_statistics">  
			<% deal_statuses.each do |deal_status| %>   
			<tr>
				<td>
					<span class="deal-status" style=<%= "background-color:#{deal_status.color_name};color:white;" %> >
						<%= link_to "#{deal_status.name}(#{@project ? @project.deals.visible.count(:conditions => {:status_id => deal_status.id}) : Deal.visible.count(:conditions => {:status_id => deal_status.id})})".html_safe, {:controller => "deals", :action => "index", :status_id => deal_status.id, :project_id => @project } %> 
					</span>             
				</td>
				<td>
					<strong>
						<%=  @project ? deals_sum_to_currency(@project.deals.visible.sum(:price, :conditions => {:status_id => deal_status.id}, :group => :currency)) : deals_sum_to_currency(Deal.visible.sum(:price, :conditions => {:status_id => deal_status.id}, :group => :currency)) %>
					</strong>  
				</td>
			</tr>
			<% end %>
		</table>
	</div>
<% end %>

app/views/deals/_list.html.erb
<%= form_tag({}) do -%>	
	<%= hidden_field_tag 'back_url', url_for(params) %>  
	<%= hidden_field_tag 'project_id', @project.id if @project %>
<div class="autoscroll">
    <table class="list">
      <thead>      
      <tr>
        <th class="checkbox hide-when-print"><%= link_to image_tag('toggle_check.png'), {}, :onclick => 'toggleIssuesSelection(this); return false;',
                                                           :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
        </th>
        <%= sort_header_tag('id', :caption => '#', :default_order => 'desc') %>
        <%= sort_header_tag('status', :caption => l(:field_contact_status), :default_order => 'asc') %>
        <%= sort_header_tag('name', :caption => l(:field_name), :default_order => 'desc') %>
        <th><%= l(:field_deal_contact) %></th>
        <%= sort_header_tag('category', :caption => l(:field_category), :default_order => 'desc') %>
        <%= sort_header_tag('due_date', :caption => l(:field_due_date), :default_order => 'desc') %>
        <%= sort_header_tag('probability', :caption => l(:label_crm_probability), :default_order => 'desc') %>
        <%= sort_header_tag('price', :caption => l(:field_deal_price), :default_order => 'desc') %>
      </tr>
      </thead>
      <% @deals.each do |deal| %>
      <tr style="text-align: center;white-space: nowrap;" class="hascontextmenu deal <%= cycle('odd', 'even') %> status-<%= deal.status_id %> status-type-<%= deal.status.status_type if deal.status %>">
        <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", deal.id, false, :id => nil) %></td>			
        <td class="id"><%= link_to deal.id, deal_path(deal) %></td>
        <td class="status"><%= deal.status.name if deal.status %></td>
        <td class="name" style="text-align:left;width:50%;"><%= link_to deal.name, deal_path(deal) %></td>
        <td class="contact" style="text-align:left;"><%= !deal.contact.blank? ? link_to_contact(deal.contact).html_safe : "" %></td>
        <td class="category"><%= deal.category.name if deal.category %></td>
        <td class="due_date"><%= format_date(deal.due_date) %></td>
        <td class="probability"><%= deal.probability.to_s + "%" unless deal.probability.blank? %></td>
        <td class="price" style="text-align:right;"><%= deal_price(deal) %></td>
      </tr>
      <% end %>
      <tr class="total">
        <th colspan="7" class="title" style="text-align:right;"> <%= "#{l(:label_total)} (#{@deals_count}):" %> </th> 
        <th colspan="2" class="sum" style="text-align:right;">
          <%= deals_sum_to_currency(@deals_sum).gsub(' / ', '<br/>').html_safe %>
        </th>
      </tr>      
    </table>
</div>    

<% end %>
<p class="pagination"><%= pagination_links_full @deals_pages, @deals_count %></p>

app/views/deals/_list_excerpt.html.erb
<%= form_tag({}) do -%>	
	<%= hidden_field_tag 'back_url', url_for(params) %>  
	<%= hidden_field_tag 'project_id', @project.id if @project %>
	<div class="autoscroll">
	<table class="contacts index">
	<tbody>
    <% @deals.each do |deal| %>
		<tr class="hascontextmenu <%= deal.status_id %>  <%= cycle('odd', 'even') %> ">     
			<td class="checkbox">
				<%= check_box_tag "ids[]", deal.id, false, :onclick => "toggleContact(event, this);" %>
			</td>
			<td class="avatar">
					<%= link_to avatar_to(deal, :size => "32"), {:controller => 'deals', :action => 'show', :id => deal.id}, :id => "avatar" %>
			</td>         
			<td class="name">
					<h1 class="deal_name"><%= link_to deal.name, :controller => 'deals', :action => 'show', :id => deal.id %></h1>
					<h2>
						<%= link_to_source(deal.contact) if deal.contact %>    
					
					</h2>
			</td>
		
			<td class="info"> 
				<div class="deal-sum"><strong><%= deal_price(deal) %></strong>  
					<% if deal.status && deal.project.deal_statuses.any? %>
          <%= deal_status_tag(deal.status) %>
					<% end %>
				</div>
				<div class="description" >  
					<%= h deal.category %> 
				</div>
			</td>
		</tr>
    <% end %>
		<tr class="total">
			<th/>
			<th/>
				<th class="title"> <%= "#{l(:label_total)} (#{@deals_count}):" %> </th> 
			<th class="sum">
				<%= deals_sum_to_currency(@deals_sum).gsub(' / ', '<br/>').html_safe %>
			</th>
		</tr>
	</tbody>  
  </table>
  </div>

<% end %>   

<p class="pagination"><%= pagination_links_full @deals_pages, @deals_count %></p>

app/views/deals/_process_item.html.erb
<% show_info = true if show_info.nil? %>  
<% show_author = true if !show_author.nil? %>  

<div id=<%="note_#{process_item.id}"%>>
	<table class="note_data">
		<tr>    
			
			<% if show_info %>
			  <% if show_author %>
    			<td class="avatar"><%= link_to avatar(process_item.author, :size => "32"), note_source_url(process_item.deal), :id => "avatar" %></td> 
			  <% else %>
    			<td class="avatar"><%= link_to avatar_to(process_item.deal, :size => "32"), note_source_url(process_item.deal), :id => "avatar" %></td> 
    		  <% end %>	
			<% end %>
			
			<td class="name">  
				<h4> 
          <%# note_type_icon(process_item) %>  
					<%= link_to_source(process_item.deal) + "," if show_info %> 
					<%= authoring_note process_item.created_at, process_item.author %> 
				</h4> 
				<div class="wiki note">   
	 				<%= deal_status_tag(process_item.from) + " &rarr; ".html_safe if process_item.from %><%= deal_status_tag(process_item.to) if process_item.to %>
				</div>
			</td>
 		</tr>
	</table>

</div>

app/views/deals/_related_deals.html.erb
<div id="deals">

<div class="contextual">
	<%= link_to_if_authorized l(:label_deal_new), {:controller => 'deals', :action => 'new', :project_id => @project, :contact_id => @contact} %>
</div>

<h3><%= "#{l(:label_deal_plural)}" %> <%= " - #{deals_sum_to_currency(@deals.select{|d| d.open? && !d.price.blank?}.group_by(&:currency).map{|k, v| [k, v.sum(&:price)]})}".html_safe if @deals.detect{|d| d.open? && !d.price.blank?} %></h3>     

<% if @deals.any? %>
	<table class="related_deals">  
	<% @deals.each do |deal| %>  
		<tr>
			<td class="name" style="vertical-align: top;">
				<h4>
					<%= link_to deal.name, {:controller => 'deals', :action => 'show', :id => deal.id } %>
				</h4>  
					<%= deal_price(deal).html_safe %>  
					<% if deal.status %>  
					<span class="deal-status" style = <%= "background-color:#{deal.status.color_name};color:white;" %> >
						<%= h deal.status %> 
					</span>
					<% end %>               
			</td>
		</tr>
	<% end %>
	</table>
<% end %>                        
</div>

app/views/deals/edit.html.erb
<h2><%= l(:label_deal_edit_information) %></h2>

<%= labelled_form_for :deal, @deal, :url => {:action => 'update', :id => @deal}, :html => {:method => :put } do |f|  %>
  <%= render :partial => 'form', :locals => {:f => f}  %>
  <%= submit_tag l(:button_save) -%>
<% end -%>

<% content_for :header_tags do %>
	<%= robot_exclusion_tag %>
<% end %>

app/views/deals/new.html.erb
<h2><%= l(:label_deal_new) %></h2>

<%= labelled_form_for :deal, @deal, :url => {:action => 'create', :project_id => @project} do |f|  %>
  <%= render :partial => 'form', :locals => {:f => f}  %>
  <%= submit_tag l(:button_save) -%>
  <%= submit_tag l(:button_create_and_continue), :name => 'continue' %>
<% end -%>


<% content_for :header_tags do %>
	<%= robot_exclusion_tag %>
<% end %>